# Generated by Django 5.2.8 on 2026-01-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_severityremedy_delete_severityguideline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depressionanswer',
            old_name='question',
            new_name='question_text',
        ),
        migrations.AlterField(
            model_name='severityremedy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='severity_remedies/'),
        ),
        migrations.AlterField(
            model_name='severityremedy',
            name='severity',
            field=models.CharField(choices=[('Minimal', 'Minimal'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='severityremedy',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
