# Generated by Django 5.2.8 on 2026-01-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_rename_question_depressionanswer_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severityremedy',
            name='severity',
            field=models.CharField(choices=[('Minimal', 'Minimal'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='severityremedy',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
